name: AI 코드 리뷰

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.py'
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: AI 코드 리뷰 실행
        id: ai-review
        uses: coderabbitai/ai-pr-reviewer@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          silent_mode: false
          review_simple_changes: true
          review_comment_lgtm: true
          language: ko
          path_filters: |
            **/*.py
            **/*.js
            **/*.jsx
            **/*.ts
            **/*.tsx
          openai_light_model: gpt-3.5-turbo-16k
          openai_heavy_model: gpt-4
          openai_timeout_ms: 120000
          max_files_to_review: 50
          max_review_message_size: 65535
          disable_review_comment: false
          extra_instructions: |
            - 코드 리뷰를 한국어로 작성해 주세요.
            - 코드가 Python 코딩 스타일 가이드(PEP 8)를 준수하는지 확인해 주세요.
            - 함수와 클래스에 적절한 문서화(docstring)가 있는지 확인해 주세요.
            - 단일 책임 원칙을 준수하는지 확인해 주세요.
            - 코드 중복이 있는지 확인하고 개선 방법을 제안해 주세요.
            - 변수명과 함수명이 의미를 명확하게 표현하는지 확인해 주세요.
            - 잠재적인 버그나 성능 문제를 찾아주세요.
            - 보안 취약점이 있는지 확인해 주세요.
            - 긍정적인 피드백도 함께 제공해 주세요.
            - 모든 피드백에는 왜 개선이 필요한지 이유를 설명해 주세요.
            - 개선 제안에는 가능한 한 구체적인 코드 예시를 포함해 주세요.
            - 코드 스타일은 '한국 개발자 스타일 가이드'를 따라주세요.
      - name: AI 요약 생성
        id: ai-summary
        if: steps.ai-review.outcome == 'success'
        uses: coderabbitai/ai-pr-reviewer@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          summarize: true
          summary_only: true
          language: ko
          openai_light_model: gpt-3.5-turbo-16k
          openai_heavy_model: gpt-4
          openai_timeout_ms: 120000
          extra_instructions: |
            - PR 요약을 한국어로 작성해 주세요.
            - 변경된 내용을 간결하게 요약해 주세요.
            - 주요 기능 변경 사항을 강조해 주세요.
            - 잠재적인 이슈나 주의 사항을 언급해 주세요.
            - 코드 품질에 대한 전반적인 평가를 포함해 주세요.
            - 이 PR의 목적과 가치를 명확하게 설명해 주세요. 

